### ISSUE TITLE
A strange payu error

### ISSUE THREAD

**Issue by AndyHoggANU** [payu-org/payu#134]
I've just cloned a recent run, and can't seem to run payu:

```Traceback (most recent call last):
  File "/jobfs/local/pbs/mom_priv/jobs/1635267.r-man2.SC", line 9, in <module>
    run_cmd.runscript()
  File "/apps/payu/0.9.2/lib/payu/subcommands/run_cmd.py", line 122, in runscript
    expt.setup()
  File "/apps/payu/0.9.2/lib/payu/experiment.py", line 347, in setup
    model.setup()
  File "/apps/payu/0.9.2/lib/payu/models/cice.py", line 166, in setup
    self.ice_nml_fname)
  File "/apps/python/2.7.11/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

Any suggestions welcome - otherwise I will clean out and try again.
Run is in `~amh157/payu/025deg_jra55_iaf_pipes`

**Comment by marshallward** [comment]
Can you try 0.10?  This looks like it may have already been fixed.

**Comment by marshallward** [comment]
Actually, looking further, this probably was not fixed in 0.10.

But it is certainly related to the problems of relying on output configs when absent from the restart directory.  I think Aidan and Nic are trying to sort this out, so probably best to reach out to Aidan.

**Comment by marshallward** [comment]
BTW this seems to be a repeat of #87, the issue that will never die...

**Comment by aidanheerdegen** [comment]
No further information or examples have been reported. Closing.
