### ISSUE TITLE
ghsetup fails with local remotes

### ISSUE THREAD

**Issue by aidanheerdegen** [payu-org/payu#219]
`ghsetup` failed when I had the following remotes defined
```
$ git remote -v
origin  /home/502/aph502/scratch_v45/HenkTestRun (fetch)
origin  /home/502/aph502/scratch_v45/HenkTestRun (push)
```
with this error message
```
Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.01/bin/payu", line 10, in <module>
    sys.exit(parse())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.01/lib/python3.7/site-packages/payu/cli.py", line 60, in parse
    run_cmd(**args)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.01/lib/python3.7/site-packages/payu/subcommands/ghsetup_cmd.py", line 23, in runcmd
    expt.runlog.github_setup()
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.01/lib/python3.7/site-packages/payu/runlog.py", line 223, in github_setup
    for r in git_remote_out.split('\n') if r])
TypeError: a bytes-like object is required, not 'str'
```

**Comment by aidanheerdegen** [comment]
Also this might be an issue:


> You recently used a password to access an endpoint through the GitHub API using python-requests/2.22.0. We will deprecate basic authentication using password to this endpoint soon:
> 
> https://api.github.com/user/repos?page=1&per_page=100
> 
> We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.

**Comment by angus-g** [comment]
Looks like it would fail regardless of the remotes? `subprocess.check_output()` returns bytes, which you can't split by a string.

**Comment by aidanheerdegen** [comment]
Yeah, maybe. I sort of assumed it must have worked at some point, but maybe I never ran that command under `python3.x`

**Comment by aidanheerdegen** [comment]
Yeah confirmed same error regardless of remote. Deleted remotes got the same error.

I liked ASCII.

**Comment by aidanheerdegen** [comment]
`ghsetup` is no longer being maintained. Will close this.
