### ISSUE TITLE
quit job if one of submodel's executables is not found.

### ISSUE THREAD

**Issue by HoWol76** [payu-org/payu#231]
Situation:
    one of the submodel's executables in config.yaml contains a typo, is not found.

Current behaviour:
    executable is excluded from manifest, but other submodels are started. They wait for the missing submodel's data until the walltime runs out.

Expected behaviour:
   payu refuses to submit run, or exits run early with informative error message.

**Comment by aidanheerdegen** [comment]
Seems reasonable. I thought `payu` checked if there was an executable. Which (sub)model was this @HoWol76?

**Comment by HoWol76** [comment]
In my case, it was CICE

**Comment by aidanheerdegen** [comment]
Can no longer recreate this issue.

Tested by cloning a config

```
payu clone -B release-1deg_jra55_ryf -b test https://github.com/ACCESS-NRI/access-om2-configs.git release-1deg_jra55_ryf
```

Ran `payu setup` and confirmed it worked fine. Change the name of the `cice5` executable to a name that does not exist and it exited:
```
Traceback (most recent call last):
  File "/g/data/vk83/prerelease/apps/base_conda/envs/payu-dev-20260519T055309Z-27624d9/bin/payu", line 6, in <module>
    sys.exit(parse())
  File "/g/data/vk83/prerelease/apps/base_conda/envs/payu-dev-20260519T055309Z-27624d9/lib/python3.10/site-packages/payu/cli.py", line 65, in parse
    run_cmd(**args)
  File "/g/data/vk83/prerelease/apps/base_conda/envs/payu-dev-20260519T055309Z-27624d9/lib/python3.10/site-packages/payu/subcommands/setup_cmd.py", line 28, in runcmd
    expt.setup(force_archive=force_archive)
  File "/g/data/vk83/prerelease/apps/base_conda/envs/payu-dev-20260519T055309Z-27624d9/lib/python3.10/site-packages/payu/experiment.py", line 63, in wrapper
    result = func(self, *args, **kwargs)
  File "/g/data/vk83/prerelease/apps/base_conda/envs/payu-dev-20260519T055309Z-27624d9/lib/python3.10/site-packages/payu/experiment.py", line 532, in setup
    model.setup()
  File "/g/data/vk83/prerelease/apps/base_conda/envs/payu-dev-20260519T055309Z-27624d9/lib/python3.10/site-packages/payu/models/cice5.py", line 70, in setup
    super(Cice5, self).setup()
  File "/g/data/vk83/prerelease/apps/base_conda/envs/payu-dev-20260519T055309Z-27624d9/lib/python3.10/site-packages/payu/models/cice.py", line 164, in setup
    super(Cice, self).setup()
  File "/g/data/vk83/prerelease/apps/base_conda/envs/payu-dev-20260519T055309Z-27624d9/lib/python3.10/site-packages/payu/models/model.py", line 314, in setup
    raise FileNotFoundError(
FileNotFoundError: Executable for ice model not found on path: /scratch/.../access-om2/bin/cice_wrong.exe
```

Got the same error when an absolute path for the executable was defined.

Closing.
