### ISSUE TITLE
Following docs results in failed payu run (payu `v1.1.5`)

### ISSUE THREAD

**Issue by manodeep** [payu-org/payu#543]
I am following the instructions for the [stable docs](https://payu.readthedocs.io/en/stable/), specifically:

```sh
mkdir new_expt; cd new_expt
payu init -m mom
payu run
```

Following the steps, the job submits fine (the first attempt took a long time for the init stage and that job submission did not work, this second attempt worked - not sure what happened there)

```sh
[~/climate_model_experiments/mom_expt @gadi09] payu init -m mom
payu: warning: Configuration file config.yaml not found!
laboratory path:  /scratch/tm70/ms2335/mom
binary path:  /scratch/tm70/ms2335/mom/bin
input path:  /scratch/tm70/ms2335/mom/input
work path:  /scratch/tm70/ms2335/mom/work
archive path:  /scratch/tm70/ms2335/mom/archive
[~/climate_model_experiments/mom_expt @gadi09] payu run
payu: warning: Configuration file config.yaml not found!
payu: Found modules in /opt/Modules/v4.3.0
qsub -q normal -P tm70 -l ncpus=1 -l mem=4GB -N mom_expt -l wd -j n -v PAYU_PATH=/g/data/vk83/apps/payu/1.1.5/bin,MODULESHOME=/opt/Modules/v4.3.0,MODULES_CMD=/opt/Modules/v4.3.0/libexec/modulecmd.tcl,MODULEPATH=/g/data/tm70/ms2335/spack/0.22/release/modules/linux-rocky8-x86_64:/g/data/vk83/modules:/g/data/tm70/ms2335/spack/0.22/release/modules/linux-rocky8-x86_64:/etc/scl/modulefiles:/etc/scl/modulefiles:/etc/scl/modulefiles:/opt/Modules/modulefiles:/opt/Modules/v4.3.0/modulefiles:/apps/Modules/modulefiles -l storage=gdata/vk83 -- /g/data/vk83/apps/payu/1.1.5/bin/python3.10 /g/data/vk83/apps/payu/1.1.5/bin/payu-run
131330081.gadi-pbs
[~/climate_model_experiments/mom_expt @gadi09] q

gadi-pbs: 
                                                                 Req'd  Req'd   Elap
Job ID               Username Queue    Jobname    SessID NDS TSK Memory Time  S Time
-------------------- -------- -------- ---------- ------ --- --- ------ ----- - -----
131330081.gadi-pbs   ms2335   normal-* mom_expt      --    1   1  4096m 10:00 Q   -- 
```

but then I get the following output (after the model runs and finishes very quickly)

```sh
[~/climate_model_experiments/mom_expt @gadi09] cat mom_expt.e131330081 
Traceback (most recent call last):
  File "/g/data/vk83/apps/payu/1.1.5/bin/payu-run", line 10, in <module>
    sys.exit(runscript())
  File "/g/data/vk83/apps/payu/1.1.5/lib/python3.10/site-packages/payu/subcommands/run_cmd.py", line 121, in runscript
    lab = Laboratory(run_args.model_type, run_args.config_path,
  File "/g/data/vk83/apps/payu/1.1.5/lib/python3.10/site-packages/payu/laboratory.py", line 30, in __init__
    raise ValueError('Cannot determine model type.')
ValueError: Cannot determine model type.
[~/climate_model_experiments/mom_expt @gadi09] cat mom_expt.o131330081 
payu: warning: Configuration file config.yaml not found!

======================================================================================
                  Resource Usage on 2024-12-20 15:23:53:
   Job Id:             131330081.gadi-pbs
   Project:            tm70
   Exit Status:        1
   Service Units:      0.00
   NCPUs Requested:    1                      NCPUs Used: 1               
                                           CPU Time Used: 00:00:00        
   Memory Requested:   4.0GB                 Memory Used: 261.51MB        
   Walltime requested: 10:00:00            Walltime Used: 00:00:02        
   JobFS requested:    100.0MB                JobFS used: 0B              
======================================================================================
[~/climate_model_experiments/mom_expt @gadi09] payu --version
payu 1.1.5
```

**Comment by jo-basevi** [comment]
Thanks for opening this issue- it looks like the docs need updating! I think `payu init` command just creates empty directories for the payu laboratory - e.g. work, archive and input directories. But it doesn't set up a configuration file, `config.yaml`, which specifies the inputs and model executables needed to run an experiment. 

For running an experiment with payu, a common workflow is to clone a pre-existing configuration repository. For example, in [running ACCESS-OM2 docs](https://access-hive.org.au/models/run-a-model/run-access-om/#get-access-om2-configuration), it clones the [ACCESS-NRI/access-om2-configs](https://github.com/ACCESS-NRI/access-om2-configs/tree/release-1deg_jra55_ryf) repository and uses a configuration branch, e.g. `release-1deg_jra55_ryf`.

For creating an experiment from scratch, there's some payu documentation here on setting up a `config.yaml` file https://payu.readthedocs.io/en/stable/usage.html#create-experiment. I think the `config.yaml` in the example requires an input and executable to run, e.g.
```
exe: fms_MOM_solo.x
input: bowl1
```
So needs a `bowl1` input copied to the `control` directory (e.g. `new_expt`), or in the `/scratch/${PROJECT}/${USER}/${MODEL}/input` directory and a `fms_MOM_solo.x` model executable added to the `/scratch/${PROJECT}/${USER}/${MODEL}/bin` directory.

**Comment by manodeep** [comment]
Thanks @jo-basevi :) 

As the newbie in climate models, I have no idea of the typical workflow and hence run into such issues where some steps might be obvious to people working in the field. Still might be good to update the docs to explicitly include the steps that you have just outlined here.
